# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc8411b6e9e90e015dda12b18981ebb12cffa92534c03b1578cfcf57304007cda98ec2c70426c04fe4d46a01e8586fa4fb9f01bbc9528868a2499456fd4f4b61

test:
  secret_key_base: 5f4011868e4d24585142e18035955965232baa4e19458eb24d25653934db990059e65511d8041c684e298904ea92cf1a0d58c40f5db14b36eea0c8a70dedf6ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
